# Define base image
FROM continuumio/miniconda3
 
# Set working directory for the project
WORKDIR /app
 
RUN apt-get update
RUN apt-get install -y -q libxi6 libgconf-2-4 libxfixes-dev libxcursor1 libxdamage-dev libxcomposite-dev libxrandr-dev libxinerama1

# Create Conda environment from the YAML file
# COPY environment.yml .
# RUN conda env create -f environment.yml
RUN conda create --name gt -c conda-forge graph-tool python=2.7

 
# Override default shell and use bash
SHELL ["conda", "run", "-n", "gt", "/bin/bash", "-c"]
 
# Activate Conda environment and check if it is working properly
RUN echo "Making sure flask is installed correctly..."
RUN python -c "from graph_tool.all import *"
 
# Python program to run in the container
COPY script.py .
ENTRYPOINT ["conda", "run", "-n", "gt", "python", "script.py"]
